apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-app
  namespace: default
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: your-git-repo-url
    path: /
    targetRevision: HEAD
  project: default
